services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odpc
      POSTGRES_PASSWORD: odpc
      POSTGRES_DB: odpc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
